name: Deploy to Vercel (Staging)

on:
  push:
    branches:
      - stg

jobs:
  deploy-stg:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Vercel Environment
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/stg" ]]; then
            echo "VERCEL_ENV=preview-rencanakanid-stg" >> $GITHUB_ENV
          else
            echo "VERCEL_ENV=production-rencanakanid-stg" >> $GITHUB_ENV
          fi

      - name: Debug Environment
        run: |
          echo "Using Vercel Environment: $VERCEL_ENV"
          echo "VERCEL_TOKEN length: ${#VERCEL_TOKEN}"
          echo "VERCEL_PROJECT_ID length: ${#VERCEL_PROJECT_ID}"
          echo "VERCEL_ORG_ID length: ${#VERCEL_ORG_ID}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STG }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to Vercel (Staging)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_STG }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          npx vercel --token="$VERCEL_TOKEN" --project="$VERCEL_PROJECT_ID" --org="$VERCEL_ORG_ID" --confirm --env=$VERCEL_ENV
